### ISSUE TITLE
Possible issue with nesting

### ISSUE THREAD

**Issue by ypantig** [redacademy/terra-spring-2019#10]
It looks like the CSS is nested under `.page-contact-us` and for lines 2 and 14, again nested under `.page-contact-us`. To solve this, you can remove the `.page-contact-us` for the two lines mentioned since it's already nested under that.

https://github.com/redacademy/terra-spring-2019/blob/c3b27b41b813a36651649d6c89c93469f7e976e3/themes/terra/sass/_page-contact-us.scss#L2-L12

https://github.com/redacademy/terra-spring-2019/blob/c3b27b41b813a36651649d6c89c93469f7e976e3/themes/terra/sass/_page-contact-us.scss#L14-L16

**Comment by mizzta** [comment]
fixed.
