### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by benorgan** [redacademy/terra-spring-2019#12]
There are a few issues with your image sizing on the homepage (e.g. for https://terra.van.cp.academy.red/wp-content/uploads/2019/06/Home-OurMission-1.jpg)

**Full size image being used**
The original image is ~2600px wide but you're displaying it at ~600px - you can use WordPress thumbnails (https://codex.wordpress.org/Post_Thumbnails#Thumbnail_Sizes) to resize this image. To do this in your front-page template you'll need to do the following:

1. `$image_id   = attachment_url_to_postid( $image_url );` where `$image_url` is the CFS field
2. `$thumbnail_url = wp_get_attachment_image_src( $image_id, 'medium_large' );` - medium_large is 768px wide, you can choose another size if that's more appropriate
3. Output the <img> element using the `$thumbnail_url` instead of the field from CFS

**Image being skewed**
The way you've resized the image in CSS is causing it to be distorted as the aspect ratio has been changed. To fix this you should set the height to auto rather than a pixel value. Or alternatively you can wrap the image in a containing <div> which is a set size and set overflow to hidden (like we did for the product grid with Inhabitent).

**Comment by benorgan** [comment]
This also seems to be the case where you've used CFS images elsewhere in your code. In this case you could add a function to functions.php that creates the <img> element with the thumbnail URL and then just call this function rather than copying and pasting the same code repeatedly.

**Comment by mizzta** [comment]
resized the uploaded image.
