### ISSUE TITLE
JS error when subscribing to newsletter

### ISSUE THREAD

**Issue by benorgan** [redacademy/terra-spring-2019#13]
I get this error on the staging site after submitting the email subscribe form: `script.min.js?ver=5.2.2:1 Uncaught TypeError: s(...).show.slideUp is not a function`

I can't quite figure out where this is coming from in your code so it's possible you've already fixed this and the code just hasn't been deployed.

**Comment by mizzta** [comment]
changed slideUp to fadeOut.
