### ISSUE TITLE
Try to avoid referencing menu IDs

### ISSUE THREAD

**Issue by benorgan** [redacademy/terra-spring-2019#19]
https://github.com/redacademy/terra-spring-2019/blob/23a123ce150d8f33a179a0769705ddfd4367fbae/themes/terra/sass/_header.scss#L153-L154

You've referenced a menu ID here in the jQuery, you'd be better off using a body class since the menu ID can change if the client edits the menu in the CMS

**Comment by Dibiase93** [comment]
changed 
 .menu-item-146, 
 .menu-item-147 

to

.menu {
          display: flex;
          justify-content: flex-end;
          .footer-menu {
            li {
              display: none;
            }
          }
Colla
