### ISSUE TITLE
Duplicate ID site-navigation

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/terra-spring-2019#2]
You currently have an id `site-navigation` in header.php which means you should update the id in footer.php to be unique e.g. `footer-navigation`

https://github.com/redacademy/terra-spring-2019/blob/bacfeade761c899bee946bfa2f2050d09709ae87/themes/terra/footer.php#L30

**Comment by mizzta** [comment]
Changed id name to footer-navigation
