### ISSUE TITLE
Change smart quotes to regular quotes

### ISSUE THREAD

**Issue by benorgan** [redacademy/terra-spring-2019#20]
https://github.com/redacademy/terra-spring-2019/blob/366439a379d18b57814e7863ebdbb697148036b0/themes/terra/sass/_variables.scss#L34-L35

You are using curly / smart quotes in your CSS for the font variables. This will probably cause an issue with your styling. This is probably due to copying and pasting from somewhere else. You should swap the curly / smart quotes to regular quotes

**Comment by mizzta** [comment]
fixed
