### ISSUE TITLE
Can't nest <h2> within another <h2>

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/terra-spring-2019#3]
At the moment this CFS field is being wrapped with an <h2> however the field is for a wysiwyg editor which allows adding more headings. To fix this you just need to change the element to something like a <div> instead of an <h2>

https://github.com/redacademy/terra-spring-2019/blob/bacfeade761c899bee946bfa2f2050d09709ae87/themes/terra/front-page.php#L27

**Comment by mizzta** [comment]
removed the cod (<h2 class="intro-fp-h2">).
