### ISSUE TITLE
Avoid using ID attributes as CSS selectors

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/terra-spring-2019#4]
See if you can get the same result without using the #text selector as it's creating a large spike when running through the CSS Specificity Graph. 

You can test this yourself by pasting style.css into the input here: https://jonassebastianohlsson.com/specificity-graph/

https://github.com/redacademy/terra-spring-2019/blob/84998cfd8e6da77372710791319b9c7ac2576f34/themes/terra/sass/_page-contact-us.scss#L78

**Comment by mizzta** [comment]
removed the code.
