### ISSUE TITLE
Duplicate ID `footer-menu`

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/terra-spring-2019#6]
This is in header.php but also in footer.php, please change one of the ids so that they are unique as you can only use an id attribute once with the same name.

https://github.com/redacademy/terra-spring-2019/blob/84998cfd8e6da77372710791319b9c7ac2576f34/themes/terra/header.php#L42

**Comment by mizzta** [comment]
we want the footer to be used in the header hamburger menu so not sure if we need to fix this. Please let us know.

**Comment by benorgan** [comment]
Duplicate IDs are not allowed with HTML and might cause issues with JavaScript. You could update the hamburger ID to be `footer-menu-hamburger`?

**Comment by BonesBird** [comment]
complete

**Comment by BonesBird** [comment]
removed footer ID from header.php
