### ISSUE TITLE
Consider making this into a custom field

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/terra-spring-2019#8]
Since this is hardcoded to gofundme.com I think the client will likely want to change this once they have a gofundme campaign setup e.g. https://www.gofundme.com/cardsforcats

https://github.com/redacademy/terra-spring-2019/blob/84998cfd8e6da77372710791319b9c7ac2576f34/themes/terra/page-support-us.php#L40

**Comment by mizzta** [comment]
changed to CFS button instead of hardcoded.
